ZayShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('general.urls')),
    path('store/', include('store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from store import views

urlpatterns = [
    path('', views.display_products, name="products"),
    path('products/<slug:slug>/', views.products_filter, name="products_filter"),
    path('men-products/', views.filter_products_by_men, name="men_products"),
    path('women-products/', views.filter_products_by_women, name="women_products"),
    path('featured-products/', views.featured_products, name="featured_products"),
    path('product-letters/', views.filter_products_by_letter, name="product_letters"),
    path('product/<slug:slug>/', views.single_product, name="single_product"),
]

store/models.py
import secrets

from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

from common.models import BaseModel


# Create your models here.


class Country(BaseModel):
    name = models.CharField(max_length=200, unique=True)
    code = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Countries"


class Customer(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255, null=True)
    email = models.EmailField(null=True)


class Category(BaseModel):
    name = models.CharField(max_length=255, null=True)
    slug = AutoSlugField(populate_from="name", unique=True, always_update=True, null=True)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.name}"


class SubCategory(BaseModel):
    name = models.CharField(max_length=255, null=True)
    slug = AutoSlugField(populate_from="name", unique=True, always_update=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, related_name="sub_category")

    class Meta:
        ordering = ["-created"]
        verbose_name = "Sub Category"
        verbose_name_plural = "Sub Categories"

    def __str__(self):
        return f"{self.name} - {self.category}"


class Size(BaseModel):
    name = models.CharField(max_length=255, null=True, unique=True, blank=True)

    class Meta:
        ordering = ["created"]

    def __str__(self):
        return f"{self.name}"


class Color(BaseModel):
    name = models.CharField(max_length=255, null=True, unique=True, blank=True)

    class Meta:
        ordering = ["created"]

    def __str__(self):
        return f"{self.name}"


class SelectProductManager(models.Manager):
    def get_queryset(self):
        return super(SelectProductManager, self).get_queryset().select_related('category')


class Product(BaseModel):
    ALL_GENDER = "A"
    ALL_MALE = "M"
    ALL_FEMALE = "F"
    GENDER_CHOICES = (
        (ALL_GENDER, "ALL"),
        (ALL_MALE, "MALE"),
        (ALL_FEMALE, "FEMALE"),
    )
    objects = models.Manager()
    selected = SelectProductManager()
    name = models.CharField(max_length=255, null=True)
    slug = AutoSlugField(populate_from="name", unique=True, always_update=True, null=True)
    category = models.ForeignKey(SubCategory, on_delete=models.SET_NULL, null=True, related_name="products")
    description = models.TextField(null=True)
    available_color = models.ManyToManyField(Color, blank=True)
    specifications = models.TextField(null=True, blank=True)
    brand = models.CharField(max_length=255, null=True, blank=True)
    gender = models.CharField(max_length=255, choices=GENDER_CHOICES, default=ALL_GENDER, null=True)
    sizes = models.ManyToManyField(Size, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(0)], null=True)
    available_quantity = models.PositiveIntegerField(default=0, null=True)
    featured = models.BooleanField(default=None, null=True)

    class Meta:
        ordering = ["-created", "name"]

    def __str__(self):
        return f"{self.name} = {self.category}"

    @property
    def display_sizes(self):
        sizes_list = []
        for size in self.sizes.values_list('name', flat=True):
            sizes_list.append(size)
        sizes = '/'.join(str(item) for item in sizes_list)
        return sizes

    @property
    def display_color(self):
        colors_list = []
        for color in self.available_color.values_list('name', flat=True):
            colors_list.append(color)
        colors = '/'.join(str(item) for item in colors_list)
        return colors


class ProductImage(BaseModel):
    product = models.ForeignKey(Product, related_name="images", on_delete=models.CASCADE)
    image = ProcessedImageField(processors=[ResizeToFill(257, 343)], format='JPEG', options={'quality': 60}, null=True)

    def __str__(self):
        return self.product.name

    @property
    def image_url(self):
        try:
            url = self.image.url
        except:
            url = None
        return url


class ShippingAddress(BaseModel):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, related_name="address")
    first_name = models.CharField(max_length=1000, null=True)
    last_name = models.CharField(max_length=1000, null=True)
    email = models.EmailField(max_length=1000, null=True, blank=True)
    phone = models.CharField(max_length=15, null=True)
    address1 = models.CharField(max_length=1000, null=True)
    address2 = models.CharField(max_length=1000, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.IntegerField(null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Shipping Addresses'

    def __str__(self):
        return f"{self.customer} = {self.order}"


class Order(BaseModel):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, related_name="order")
    tx_ref = models.CharField(max_length=10, null=True, blank=True, unique=True)
    placed_at = models.DateTimeField(auto_now_add=True)
    verified = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(ShippingAddress, on_delete=models.CASCADE, blank=True, null=True)
    payment_complete = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.customer} = {self.payment_complete}"

    def save(self, *args, **kwargs) -> None:
        while not self.tx_ref:
            allowed_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789"
            unique_code = "".join(secrets.choice(allowed_chars) for i in range(10))
            tx_ref = unique_code
            similar_obj_tx_ref = Order.objects.filter(tx_ref=tx_ref)
            if not similar_obj_tx_ref:
                self.tx_ref = tx_ref
        super().save(*args, **kwargs)


class OrderItem(BaseModel):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, related_name='items', null=True)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, related_name="orderitems")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name='orderitems', null=True)
    color = models.ForeignKey(Color, related_name="orderitems", on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()
    unit_price = models.DecimalField(max_digits=6, decimal_places=2)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.product} = {self.quantity} = {self.unit_price}"

    @property
    def get_total(self):
        product = self.product
        price = product.price
        self.unit_price = price * self.quantity
        return self.unit_price


class Cart(BaseModel):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, related_name="carts")
    order_items = models.ForeignKey(OrderItem, on_delete=models.SET_NULL, null=True, related_name="carts")

store/forms.py
from django import forms

from store.models import Product


class DetailForm(forms.ModelForm):
    quantity = forms.IntegerField(min_value=1)

    class Meta:
        model = Product
        fields = ["sizes", "quantity"]
        widgets = {
            "sizes": forms.CheckboxSelectMultiple
        }

    def __init__(self, *args, **kwargs):
        super(DetailForm, self).__init__(*args, **kwargs)

        # self.fields['sizes'].widget.attrs.update({'class': 'form-check'})
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})

store/views.py
import random
import string

from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower, Substr
from django.shortcuts import render, redirect

from store.forms import DetailForm
from store.models import Category, Product, SubCategory
from store.utils import paginate_products


# Create your views here.


def display_products(request):
    categories = Category.objects.all()
    products = Product.selected.all()
    if not (categories and products):
        messages.error(request, "No products available in the shop")
        return redirect('home')
    # pagination
    products, custom_range = paginate_products(request, products, 9)
    context = {"categories": categories, "products": products, "custom_range": custom_range}
    return render(request, "store/shop.html", context)


def products_filter(request, slug):
    page = 'all'
    categories = Category.objects.all()
    sub_categories = SubCategory.objects.all()
    try:
        sub_category = sub_categories.get(slug=slug)
    except SubCategory.DoesNotExist:
        messages.info(request, "Category does not exist")
        return redirect('products')
    sub_products = sub_category.products.all()
    if not sub_products.exists():
        messages.info(request, "No products in this category")
        return redirect('products')
    context = {"categories": categories, "sub_products": sub_products, "page": page}
    return render(request, "store/products_filter.html", context)


def filter_products_by_men(request):
    page = 'men'
    categories = Category.objects.all()
    men_products = Product.selected.filter(gender="M")
    if not men_products.exists():
        messages.info(request, "No products in this category")
        return redirect('products')
    context = {"categories": categories, "men_products": men_products, "page": page}
    return render(request, "store/products_filter.html", context)


def filter_products_by_women(request):
    page = 'women'
    categories = Category.objects.all()
    women_products = Product.selected.filter(gender="F")
    if not women_products.exists():
        messages.info(request, "No products in this category")
        return redirect('products')
    context = {"categories": categories, "women_products": women_products, "page": page}
    return render(request, "store/products_filter.html", context)


def featured_products(request):
    page = 'featured'
    categories = Category.objects.all()
    featured = Product.selected.filter(featured=True)
    if not featured:
        messages.info(request, 'No featured product')
        return redirect('products')
    context = {"categories": categories, "featured": featured, "page": page}
    return render(request, "store/products_filter.html", context)


def filter_products_by_letter(request):
    page = 'letters'
    uppercase_alphabet = string.ascii_uppercase
    categories = Category.objects.all()
    letters = Product.selected.order_by("name").annotate(first_letter=Lower(Substr('name', 1, 1)))
    letters = letters.exclude(~Q(first_letter__in=uppercase_alphabet))
    if not letters:
        messages.info(request, 'No product')
        return redirect('products')
    context = {"categories": categories, "letters": letters, "page": page}
    return render(request, "store/products_filter.html", context)


def single_product(request, slug):
    try:
        product = Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        messages.info(request, 'Product does not exist')
        return redirect('products')
    related_products = Product.selected.exclude(slug=product.slug)
    count = 16
    if related_products.count() < 6:
        count = related_products.count()
    related_products = random.sample(list(related_products), count)
    if request.method == "POST" and "buy-btn" in request.POST:
        form = DetailForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Item added to cart successfully")
            return redirect(f'/store/product/{product.slug}/')
        else:
            messages.info(request, "Failed to buy product")
            return redirect(f'/store/product/{product.slug}/')
    elif request.method == "POST" and "cart-btn" in request.POST:
        form = DetailForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Item added to cart successfully")
            return redirect(f'/store/product/{product.slug}/')
        else:
            messages.info(request, "Failed to add item to cart")
            return redirect(f'/store/product/{product.slug}/')
    else:
        form = DetailForm()
    context = {'product': product, "related_products": related_products, "form": form}
    return render(request, "store/shop-single.html", context)

store/templates/store/shop-single.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <!-- Open Content -->
    <section class="bg-light">
        <div class="container pb-5">
            <div class="row">
                <div class="col-lg-5 mt-5">
                    <div class="card mb-3">
                        <img class="card-img img-fluid" src="{{ product.product_main_image.url }}"
                             style="width:524px; height:524px"
                             alt="Card image cap"
                             id="product-detail">
                    </div>
                    <div class="row">
                        <!--Start Controls-->
                        <div class="col-1 align-self-center">
                            <a href="#multi-item-example" role="button" data-bs-slide="prev">
                                <i class="text-dark fas fa-chevron-left"></i>
                                <span class="sr-only">Previous</span>
                            </a>
                        </div>
                        <!--End Controls-->
                        <!--Start Carousel Wrapper-->
                        <div id="multi-item-example" class="col-10 carousel slide carousel-multi-item"
                             data-bs-ride="carousel">
                            <!--Start Slides-->
                            <div class="carousel-inner product-links-wap" role="listbox">

                                <!--First slide-->
                                <div class="carousel-item active">
                                    <div class="row">
                                        <div class="col-4">
                                            <a href="#">
                                                <img class="card-img img-fluid"
                                                     src="{{ product.product_main_image.url }}"
                                                     style="width: 129px; height: 129px"
                                                     alt="Product Image 1">
                                            </a>
                                        </div>
                                        {% if product.second_product_image %}
                                            <div class="col-4">
                                                <a href="#">
                                                    <img class="card-img img-fluid"
                                                         src="{{ product.second_product_image.url }}"
                                                         style="width: 129px; height: 129px"
                                                         alt="Product Image 1">
                                                </a>
                                            </div>
                                        {% endif %}
                                        {% if product.third_product_image %}
                                            <div class="col-4">
                                                <a href="#">
                                                    <img class="card-img img-fluid"
                                                         src="{{ product.third_product_image.url }}"
                                                         style="width: 129px; height: 129px"
                                                         alt="Product Image 1">
                                                </a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                <!--/.First slide-->

                                <!--Second slide-->
                                <div class="carousel-item">
                                    <div class="row">
                                        <div class="col-4">
                                            <a href="#">
                                                <img class="card-img img-fluid"
                                                     src="{{ product.product_main_image.url }}"
                                                     style="width: 129px; height: 129px"
                                                     alt="Product Image 4">
                                            </a>
                                        </div>
                                        {% if product.fourth_product_image %}
                                            <div class="col-4">
                                                <a href="#">
                                                    <img class="card-img img-fluid"
                                                         src="{{ product.fourth_product_image.url }}"
                                                         style="width: 129px; height: 129px"
                                                         alt="Product Image 1">
                                                </a>
                                            </div>
                                        {% endif %}
                                        {% if product.fifth_product_image %}
                                            <div class="col-4">
                                                <a href="#">
                                                    <img class="card-img img-fluid"
                                                         src="{{ product.fifth_product_image.url }}"
                                                         style="width: 129px; height: 129px"
                                                         alt="Product Image 1">
                                                </a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                <!--/.Second slide-->

                            </div>
                            <!--End Slides-->
                        </div>
                        <!--End Carousel Wrapper-->
                        <!--Start Controls-->
                        <div class="col-1 align-self-center">
                            <a href="#multi-item-example" role="button" data-bs-slide="next">
                                <i class="text-dark fas fa-chevron-right"></i>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                        <!--End Controls-->
                    </div>
                </div>
                <!-- col end -->
                <div class="col-lg-7 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="h2">{{ product.name }}</h1>
                            <p class="h3 py-2">${{ product.price }}</p>
                            <p class="py-2">
                                <i class="fa fa-star text-warning"></i>
                                <i class="fa fa-star text-warning"></i>
                                <i class="fa fa-star text-warning"></i>
                                <i class="fa fa-star text-warning"></i>
                                <i class="fa fa-star text-secondary"></i>
                                <span class="list-inline-item text-dark">Rating 4.8 | 36 Comments</span>
                            </p>
                            {% if product.brand %}
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <h6>Brand:</h6>
                                    </li>
                                    <li class="list-inline-item">
                                        <p class="text-muted"><strong>{{ product.brand }}</strong></p>
                                    </li>
                                </ul>
                            {% endif %}

                            <h6>Description:</h6>
                            <p>{{ product.description|linebreaksbr }}</p>

                            {% if product.available_color %}
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <h6>Available Color :</h6>
                                    </li>
                                    <li class="list-inline-item">
                                        <p class="text-muted"><strong>{{ product.display_color }}</strong></p>
                                    </li>
                                </ul>
                            {% endif %}

                            {% if product.specifications %}
                                <h6>Specification:</h6>
                                <ul class="list-unstyled pb-3">
                                    <li>{{ product.specifications|linebreaksbr }}</li>
                                </ul>
                            {% endif %}

                            <form action="{% url 'single_product' product.slug %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="product-title" value="{{ product.name }}">
                                <div class="row">
                                    {% if product.sizes.exists %}
                                        <div class="col-auto form-group">
                                            <ul class="list-inline pb-3">
                                                <li class="list-inline-item">
                                                    <label for="id_sizes">
                                                        <b>Size: </b>
                                                    </label>
                                                <li class="list-inline-item">
                                                    {{ form.sizes }}
                                                </li>
                                            </ul>
                                        </div>
                                    {% endif %}
                                    <div class="col-auto">
                                        <ul class="list-inline pb-3">
                                            <li class="list-inline-item text-right">
                                                Quantity
                                                <input type="hidden" name="product-quanity" id="product-quanity"
                                                       value="1">
                                            </li>
                                            <li class="list-inline-item">
                                                {{ form.quantity }}
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="row pb-3">
                                    <div class="col d-grid">
                                        <button type="submit" class="btn btn-success btn-lg" name="buy-btn" value="buy">
                                            Buy Item
                                        </button>
                                    </div>
                                    <div class="col d-grid">
                                        <button type="submit" class="btn btn-success btn-lg" name="cart-btn"
                                                value="addtocard">Add To Cart
                                        </button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Close Content -->
{% endblock body %}